name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: ls
        run: |
          ls -la

      - name: Install deps
        run: sudo apt install fzf

      - name: build and test
        run: |
          ls -la
          make build
          make run
        env:
          GOFLAGS: "-mod=vendor"

      - name: install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.22.0/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.22.0

      - name: run linters
        run: $GITHUB_WORKSPACE/golangci-lint run --disable=deadcode,unused
        env:
          GOFLAGS: "-mod=vendor"